eureka:
  server:
    wait-time-in-ms-when-sync-empty: 0
    maxThreadsForPeerReplication: 0
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false

server:
  port: 8282