spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/roman1306/configuration-netflix-oss-homework.git

server:
  port: ${CONFIG_PORT:8888}
